# Generated by Django 5.1.2 on 2024-11-06 01:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
