# Generated by Django 5.1.2 on 2024-11-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_player_position_player_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_selected', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='core.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('user', 'league')},
        ),
        migrations.AddField(
            model_name='playerselection',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_selections', to='core.team'),
        ),
        migrations.DeleteModel(
            name='TeamPlayer',
        ),
        migrations.AlterUniqueTogether(
            name='playerselection',
            unique_together={('player', 'team')},
        ),
    ]
