# Generated by Django 5.1.2 on 2024-11-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_playerselection_delete_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wins',
        ),
    ]
