# Generated by Django 5.1.2 on 2024-11-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_team_user_alter_team_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
