# Generated by Django 5.1.2 on 2024-11-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_league_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='is_closed',
        ),
    ]
