# Generated by Django 5.1.2 on 2024-11-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_league_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='is_private',
        ),
    ]
